version: '3.9'
services:
  app:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=3000
      - WALLET_PRIVATE_KEY=x
      - LOG_LEVEL=info
    ports:
      - '3000:3000'
    volumes:
      - ./coverage:/project/coverage
